export const codeProjects = [
  {
    title: "cypress-cucumber-preprocessor",
    description: "Run cucumber specs with Cypress.io",
    downloads: "700k monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/cypress-cucumber-preprocessor",
    tags: ["cypress", "cucumber", "testing"],
  },
  {
    title: "wait-for-expect",
    description: "Wait for expectation to be true.",
    downloads: "3.5 mln monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/wait-for-expect",
    tags: ["tooling", "jest", "testing"],
  },
  {
    title: "modifyjs",
    description: "Modify your objects with a mongo like syntax.",
    downloads: "50k monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/modifyjs",
    tags: ["helper", "mongodb"],
  },
  {
    title: "babel-plugin-ignore-html-and-css-imports",
    description: "Ignore html and css imports in your code. Useful for testing meteor without its context",
    downloads: "67k monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/babel-plugin-ignore-html-and-css-imports",
    tags: ["babel-plugin", "html", "import"],
  },
  {
    title: "react-one-tab-enforcer",
    description: "Prevent users from opening your react app in multiple tabs",
    downloads: "2k monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/react-one-tab-enforcer",
    tags: ["react", "tab", "enforce"],
  },
  {
    title: "use-complex-state",
    description: "A small wrapper combining Redux Toolkit and useReducer with extra syntax sugar",
    downloads: "492 monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/use-complex-state",
    tags: ["react", "hooks", "state-management"],
  },
  {
    title: "jest-runner-standard",
    description: "Standard Style runner for Jest",
    downloads: "165 monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/jest-runner-standard",
    tags: ["standard", "lint", "eslint"],
  },
  {
    title: "federation-testing-tool",
    description: "Test your Apollo GraphQL Gateway / Federation micro services",
    downloads: "98 monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/federation-testing-tool",
    tags: ["GraphQL", "testing", "Apollo"],
  },
  {
    title: "pojo-observer",
    description: "A minimalist object observer that works with React hooks",
    downloads: "198 monthly downloads",
    type: "npm",
    link: "https://www.npmjs.com/package/pojo-observer",
    tags: ["react", "reactivity", "state-management"],
  },
  {
    title: "dynamodb-testing-tool",
    description: "Utilities for testing DynamoDB integrations locally",
    downloads: "",
    type: "npm",
    link: "https://www.npmjs.com/package/dynamodb-testing-tool",
    tags: ["aws", "dynamodb", "testing"],
  },
  {
    title: "why-so-loud-jest",
    description: "Silence noisy console output during Jest test runs",
    downloads: "",
    type: "npm",
    link: "https://www.npmjs.com/package/why-so-loud-jest",
    tags: ["jest", "testing", "console"],
  },
  {
    title: "cdk-typescript-tooling",
    description: "TypeScript utilities and helpers for AWS CDK projects",
    downloads: "",
    type: "npm",
    link: "https://www.npmjs.com/package/cdk-typescript-tooling",
    tags: ["aws", "cdk", "typescript"],
  },
];
